/*
 * Copyright (c) KylinSoft  Co., Ltd. 2024.All rights reserved.
 * ha-api licensed under the Mulan Permissive Software License, Version 2.
 * See LICENSE file for more details.
 * Author: bixiaoyan <bixiaoyan@kylinos.cn>
 * Date: Thu Mar 27 09:32:28 2025 +0800
 */

package models

import (
	"fmt"
	"strings"

	"gitee.com/openeuler/ha-api/settings"
	"gitee.com/openeuler/ha-api/utils"
	"github.com/sagikazarmark/slog-shim"
)

func GenerateLog() (string, error) {
	out, err := utils.RunCommand(utils.CmdGenLog)
	if err != nil {
		return "", fmt.Errorf("get kylinha log failed: %v", err)
	}

	output := strings.TrimSpace(string(out))
	if output == "" {
		return "", fmt.Errorf("loggen produced no output")
	}

	var fileName string
	var warningLines []string

	for _, line := range strings.Split(output, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}

		if strings.HasPrefix(trimmed, "kylinha-log-") && strings.HasSuffix(trimmed, ".tar.gz") {
			// 安全校验：文件名只能包含安全字符
			if !isValidLogFileName(trimmed) {
				slog.Warn("Invalid log filename from loggen", "file", trimmed)
				continue
			}
			fileName = trimmed
		} else {
			warningLines = append(warningLines, trimmed)
		}
	}

	if len(warningLines) > 0 {
		slog.Warn("Warnings from loggen", "detail", strings.Join(warningLines, "; "))
	}

	if fileName == "" {
		return "", fmt.Errorf("no valid log file generated by loggen")
	}

	filePath := filepath.Join(logStaticDir, fileName)
	// 额外安全校验：确保路径没有逃出预期目录
	if !strings.HasPrefix(filepath.Clean(filePath), filepath.Clean(logStaticDir)) {
		return "", fmt.Errorf("generated log path escapes expected directory")
	}

	return filePath, nil
}

func isValidLogFileName(name string) bool {
	// 只允许字母、数字、连字符、点、下划线
	return len(name) > 0 && len(name) < 256 && regexp.MustCompile(`^[a-zA-Z0-9._-]+$`).MatchString(name)
}